# Generated by Django 3.2.7 on 2021-12-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('desc', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('audience', models.ManyToManyField(related_name='audience', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concerts', related_query_name='concerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'концерты',
                'verbose_name_plural': 'концерт',
            },
        ),
        migrations.CreateModel(
            name='ConcertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='concerts-items', to='mainapp.concert')),
            ],
        ),
    ]
